{
 "title": "Downloads, Requests, and Logins",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Downloads and Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Downloads",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"False\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"False\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"False\"} @ start() or vector(0)\n)",
       "legendFormat": "Non DRS"
      },
      {
       "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"True\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"True\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"True\"} @ start() or vector(0)\n)",
       "legendFormat": "DRS"
      }
     ]
    },
    {
     "title": "Downloads",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_presigned_url_total{hostname=~\"$hostname\"} @ start() or vector(0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Downloads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_presigned_url_total{hostname=~\"$hostname\"} @ start() or vector(0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Downloads",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_presigned_url_total{hostname=~\"$hostname\"} @ start() or vector(0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Non DRS Data Access Requests",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"False\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"False\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"False\"} @ start() or vector(0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Non DRS Data Access Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"False\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"False\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"False\"} @ start() or vector(0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Non DRS Data Access Requests",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"False\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"False\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"False\"} @ start() or vector(0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DRS Data Access Requests",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"True\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"True\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"True\"} @ start() or vector(0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DRS Data Access Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"True\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"True\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"True\"} @ start() or vector(0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DRS Data Access Requests",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"True\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"True\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_presigned_url_total{hostname=~\"$hostname\", drs=\"True\"} @ start() or vector(0)\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total Logins",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{idp=\"ras\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{idp=\"ras\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{idp=\"ras\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "RAS"
    },
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{idp=\"google\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{idp=\"google\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{idp=\"google\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "Google"
    },
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{fence_idp=\"orcid\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{fence_idp=\"orcid\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{fence_idp=\"orcid\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "Orcid"
    },
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{shib_idp=\"urn:mace:incommon:uchicago.edu\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{shib_idp=\"urn:mace:incommon:uchicago.edu\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{shib_idp=\"urn:mace:incommon:uchicago.edu\", hostname=\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "UChicago InCommon"
    },
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{fence_idp=\"shibboleth\", shib_idp=\"https://auth.nih.gov/IDP\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{fence_idp=\"shibboleth\", shib_idp=\"https://auth.nih.gov/IDP\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{fence_idp=\"shibboleth\", shib_idp=\"https://auth.nih.gov/IDP\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "NIH"
    },
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{shib_idp=\"https://aaf.unsw.edu.au/idp/shibboleth\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{shib_idp=\"https://aaf.unsw.edu.au/idp/shibboleth\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{shib_idp=\"https://aaf.unsw.edu.au/idp/shibboleth\", hostname=\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "UNSW"
    }
   ]
  },
  {
   "title": "Total Logins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{idp=\"all\", hostname=~\"$cluster|$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{idp=\"all\", hostname=~\"$cluster|$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{idp=\"all\", hostname=~\"$cluster|$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{idp=\"all\", hostname=~\"$cluster|$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{idp=\"all\", hostname=~\"$cluster|$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{idp=\"all\", hostname=~\"$cluster|$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Logins",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{idp=\"all\", hostname=~\"$cluster|$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{idp=\"all\", hostname=~\"$cluster|$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{idp=\"all\", hostname=~\"$cluster|$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Google Logins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{idp=\"google\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{idp=\"google\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{idp=\"google\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Google Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{idp=\"google\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{idp=\"google\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{idp=\"google\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Google Logins",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{idp=\"google\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{idp=\"google\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{idp=\"google\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orcid Logins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{fence_idp=\"orcid\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{fence_idp=\"orcid\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{fence_idp=\"orcid\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orcid Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{fence_idp=\"orcid\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{fence_idp=\"orcid\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{fence_idp=\"orcid\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orcid Logins",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{fence_idp=\"orcid\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{fence_idp=\"orcid\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{fence_idp=\"orcid\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UChicago InCommon Logins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{shib_idp=\"urn:mace:incommon:uchicago.edu\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{shib_idp=\"urn:mace:incommon:uchicago.edu\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{shib_idp=\"urn:mace:incommon:uchicago.edu\", hostname=\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UChicago InCommon Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{shib_idp=\"urn:mace:incommon:uchicago.edu\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{shib_idp=\"urn:mace:incommon:uchicago.edu\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{shib_idp=\"urn:mace:incommon:uchicago.edu\", hostname=\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UChicago InCommon Logins",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{shib_idp=\"urn:mace:incommon:uchicago.edu\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{shib_idp=\"urn:mace:incommon:uchicago.edu\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{shib_idp=\"urn:mace:incommon:uchicago.edu\", hostname=\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NIH Logins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{fence_idp=\"shibboleth\", shib_idp=\"https://auth.nih.gov/IDP\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{fence_idp=\"shibboleth\", shib_idp=\"https://auth.nih.gov/IDP\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{fence_idp=\"shibboleth\", shib_idp=\"https://auth.nih.gov/IDP\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NIH Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{fence_idp=\"shibboleth\", shib_idp=\"https://auth.nih.gov/IDP\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{fence_idp=\"shibboleth\", shib_idp=\"https://auth.nih.gov/IDP\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{fence_idp=\"shibboleth\", shib_idp=\"https://auth.nih.gov/IDP\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NIH Logins",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{fence_idp=\"shibboleth\", shib_idp=\"https://auth.nih.gov/IDP\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{fence_idp=\"shibboleth\", shib_idp=\"https://auth.nih.gov/IDP\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{fence_idp=\"shibboleth\", shib_idp=\"https://auth.nih.gov/IDP\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAS Logins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{idp=\"ras\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{idp=\"ras\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{idp=\"ras\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAS Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{idp=\"ras\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{idp=\"ras\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{idp=\"ras\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAS Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{idp=\"ras\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{idp=\"ras\", hostname=~\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{idp=\"ras\", hostname=~\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UNSW Logins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{shib_idp=\"https://aaf.unsw.edu.au/idp/shibboleth\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{shib_idp=\"https://aaf.unsw.edu.au/idp/shibboleth\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{shib_idp=\"https://aaf.unsw.edu.au/idp/shibboleth\", hostname=\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UNSW Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{shib_idp=\"https://aaf.unsw.edu.au/idp/shibboleth\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{shib_idp=\"https://aaf.unsw.edu.au/idp/shibboleth\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{shib_idp=\"https://aaf.unsw.edu.au/idp/shibboleth\", hostname=\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UNSW Logins",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    # Calculates the difference between the last measurement \n    # and the first measurement in the given time_range for each \n    # timeseries, this helps identify how much additional resources\n    # were consumed in the given time_range\n    increase(\n        gen3_fence_login_total{shib_idp=\"https://aaf.unsw.edu.au/idp/shibboleth\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n    # Adds to the difference the minimum value of each timeseries, \n    # this helps to account for the timeseries that started within \n    # the given time_range with the first measurement greater than 0\n    # (not considered by the previous increase function)\n    + min_over_time(\n        gen3_fence_login_total{shib_idp=\"https://aaf.unsw.edu.au/idp/shibboleth\", hostname=\"$hostname\", container=\"fence\"}[$__range]\n    )\n)\n# Removes the timeseries measurements being carried over from before \n# the start of the time_range, this offsets the running timeseries\n# as if they had started from zero within the time_range\n- sum(\n    gen3_fence_login_total{shib_idp=\"https://aaf.unsw.edu.au/idp/shibboleth\", hostname=\"$hostname\", container=\"fence\"} @ start() or vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}