{
 "title": "Portal Traffic Stats",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Faro", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Faro User Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(session_id) (rate({service=\"frontend-app\", app_environment=\"$hostname\"} | logfmt | type != `web-vitals` [$__auto]))"
    }
   ]
  },
  {
   "title": "Faro Average Session Duration in Minutes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(\n  {service=\"frontend-app\", app_environment=\"$hostname\"} | logfmt | label_format ts=`{{ __timestamp__ | unixEpoch }}`\n    | unwrap ts\n  [$__auto]) by (session_id)\n- min_over_time(\n  {service=\"frontend-app\", app_environment=\"$hostname\"} | logfmt | label_format ts=`{{ __timestamp__ | unixEpoch }}`\n    | unwrap ts\n  [$__auto])  by (session_id)\n"
    }
   ]
  },
  {
   "title": "Browser breakdown (Faro)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(browser_name) (rate({service=\"frontend-app\", app_environment=\"$hostname\"} |= `` | logfmt | type != `web-vitals` [$__auto]))"
    }
   ]
  },
  {
   "title": "Most Common Referrer",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "{app=\"portal\", hostname=\"$hostname\"} | json | __error__=`` | http_useragent != `ELB-HealthChecker/2.0` | http_useragent != `kube-probe/1.28+`",
     "legendFormat": "{{session_id}}"
    }
   ]
  },
  {
   "title": "OS breakdown (Faro)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(browser_os) (rate({service=\"frontend-app\", app_environment=\"$hostname\"} |= `` | logfmt | type != `web-vitals` [$__auto]))"
    }
   ]
  },
  {
   "title": "Most Active User",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "{app=\"portal\", hostname=\"$hostname\"} | json | __error__=`` | http_useragent != `ELB-HealthChecker/2.0` | http_useragent != `kube-probe/1.28+`",
     "legendFormat": "{{session_id}}"
    }
   ]
  },
  { "title": "Portal Logs Based", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "User Sessions ( new query) ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by (session_id) (count_over_time({app=\"portal\", hostname=\"$hostname\"} | json | __error__=`` | http_useragent != `ELB-HealthChecker/2.0` | http_useragent != `kube-probe/1.28+` [$__auto])) > 1",
     "legendFormat": "{{session_id}}"
    }
   ]
  },
  {
   "title": "Unique User Sessions (IP based) (new Query)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "sum by (network_client_ip)(sum by (network_client_ip, session_id) (count_over_time({app=\"portal\", hostname=\"$hostname\"} | json | __error__=`` | http_useragent != `ELB-HealthChecker/2.0` | http_useragent != `kube-probe/1.28+` [$__auto])) > 1)",
     "legendFormat": "{{session_id}}"
    }
   ]
  },
  {
   "title": "Old",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Sessions (Old Query)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "expr": "{app=\"portal\", hostname=\"$hostname\"} | json | __error__=`` | http_useragent != `ELB-HealthChecker/2.0` | http_useragent != `kube-probe/1.28+` ",
       "legendFormat": "{{session_id}}",
       "maxLines": 3000
      }
     ]
    },
    {
     "title": "Unique User Sessions (Old Query, IP based)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
     "targets": [
      {
       "expr": "{app=\"portal\", hostname=\"$hostname\"} | json | __error__=`` | http_useragent != `ELB-HealthChecker/2.0` | http_useragent != `kube-probe/1.28+`",
       "legendFormat": "{{session_id}}",
       "maxLines": 3000
      }
     ]
    }
   ]
  }
 ]
}